version: '3.9'

services:
  channel_messenger_dev:
    image: channel_messenger:latest
    build: .
    restart: unless-stopped
    command: npm run start
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
    ports:
      - $SERVER_PORT_DEV:3000
    volumes:
      - ./db:/usr/src/app/db
  channel_messenger_prod:
    image: channel_messenger:latest
    build: .
    restart: unless-stopped
    command: npm run start:prod
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    ports:
      - $SERVER_PORT_PROD:3000
    volumes:
      - ./db:/usr/src/app/db
